from .types.natives import ALLOWED_NATIVES
from .types import common_types_registry

ALLOWED_NATIVES = ALLOWED_NATIVES
ALLOWED_BUILTINS = frozenset(
    {
        "None",
        "False",
        "True",
        "abs",
        "all",
        "any",
        "bin",
        "bool",
        "bytes",
        "chr",
        "complex",
        "dict",
        "dir",
        "divmod",
        "enumerate",
        "filter",
        "format",
        "frozenset",
        "hash",
        "hex",
        "id",
        "int",
        "iter",
        "len",
        "list",
        "map",
        "max",
        "min",
        "next",
        "oct",
        "ord",
        "bytearray",
        "pow",
        "print",
        "range",
        "repr",
        "reversed",
        "round",
        "set",
        "slice",
        "sorted",
        "str",
        "sum",
        "tuple",
        "zip",
    }
)

types_registry = common_types_registry
